"""Backward-compatible entry point for the PureAutoCodeQL CLI."""

from pure_auto_codeql.cli.app import (
    AnalysisConfig,
    AnalysisOrchestrator,
    CodeQLComposeTool,
    LanguageDetector,
    LLMRole,
    MultiAgentAnalyzer,
    ProjectImportResult,
    UnifiedSourceAnalysisAgent,
    _normalize_cli_args,
    cli,
    discover_cve_assets,
    dispatch_command,
    get_llm_config,
    list_available_cases,
    list_available_providers,
    list_providers,
    list_siliconflow_models,
    main,
    parse_arguments,
    resolve_case,
    run_case_analysis,
    run_doctor,
    run_md_direct_codeql,
    run_md_source_analysis,
    run_project_import,
    validate_case,
)
from pure_auto_codeql.configuration import get_llm_config_by_provider

__all__ = [
    "AnalysisConfig",
    "AnalysisOrchestrator",
    "CodeQLComposeTool",
    "LanguageDetector",
    "LLMRole",
    "MultiAgentAnalyzer",
    "ProjectImportResult",
    "UnifiedSourceAnalysisAgent",
    "_normalize_cli_args",
    "cli",
    "discover_cve_assets",
    "dispatch_command",
    "get_llm_config",
    "get_llm_config_by_provider",
    "list_available_cases",
    "list_available_providers",
    "list_providers",
    "list_siliconflow_models",
    "main",
    "parse_arguments",
    "resolve_case",
    "run_case_analysis",
    "run_doctor",
    "run_md_direct_codeql",
    "run_md_source_analysis",
    "run_project_import",
    "validate_case",
]


if __name__ == "__main__":
    cli()
